spring.application.name=products-api

# Base de datos H2 en memoria (no requiere instalar nada)
spring.datasource.url=jdbc:h2:mem:productsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Swagger UI -> http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
