# Puerto del servidor
server.port=8080

# Base de datos H2 en memoria (no necesita instalar nada)
spring.datasource.url=jdbc:h2:mem:estudiantesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola web de H2 (para ver los datos): http://localhost:8080/h2-console
spring.h2.console.enabled=true

# Hibernate crea/actualiza la tabla automáticamente a partir de la entidad
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
